name: Build and Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy the application for"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: devops-interview-demo-${{ github.actor }}-${{ github.run_id }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Lint Code
        run: npm run lint

      - name: Build Application
        run: |
          npm run build

      - name: Deploy Application
        run: |
          aws s3 sync ./build s3://oshihealth.$ENVIRONMENT.griddalur.xyz --delete
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
